// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mssifhdrquopobjmysvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1zc2lmaGRycXVvcG9iam15c3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MDM3MDYsImV4cCI6MjA3Mjk3OTcwNn0.4Nx3wuGPB2OvL5fv9xjrs0Y_LBW_Zymeflkc6GgqNYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});